LogiCAB.Web/Controllers/VBNController.cs
using CAB.Domain.Providers;
using Ionic.Zip;
using log4net;
using LogiCAB.Web.Domain;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Net;
using System.Web.Mvc;
using System.Linq;
using LogiCAB.Web.DAL;
using CAB.Data.EF.Models;

namespace LogiCAB.Web.Controllers {
    [AuthorizeWithSessionAttribute]
    [HandleError]
    public class VBNController : BaseController {
        private ISettingsProvider _settingsProvider;

        /* IoC */
        public VBNController(
            ISettingsProvider settingsProvider,
            ILog log) : base(log)
        {
            _settingsProvider = settingsProvider;
        }

        public ActionResult Index() {
            string[] filesCode = Directory.GetFiles(Server.MapPath("~/tmp/"), "FP*.txt");
            if (filesCode.Length == 0) {
                try { 
                downloadVBNCodes();
                } catch (Exception ex) {
                    Log.ErrorFormat("Error downloading new VBNList: {0}", ex.ToString());
                    return View(new List<VBNCodeRecord>());
                }
            }
            return View(_getVBNList());
        }

        public ActionResult Link() {
            return View();
        }

        public int updateVBNExtraProperties() {
            string[] filesCode = Directory.GetFiles(Server.MapPath("~/tmp/"), "CY*.txt");
            string fileCode = filesCode[filesCode.Length - 1];
            var vbnExtraPropertiesTxt = (from line in ReadFrom(fileCode)
                               let record = ParseLineExtraProperty(line)
                               select record).ToList();
            var vbnPropDB = EFHelper.ctx.F_CAB_VBN_PROPERTIES_SPECIFIED.ToList();
            var vbnExtraPropertiesDB = (from vps in vbnPropDB
                                        select new ExtraPropertyRecord {
                                            CVPS_SEQUENCE = vps.CVPS_SEQUENCE,
                                            CVPS_VBN_CODE_D = vps.CVPS_VBN_CODE,
                                            CVPS_PROP_CODE = vps.CVPS_VBN_PROP_CODE,
                                            CVPS_MANDATORY_YN = Convert.ToInt32(vps.CVPS_MANDATORY_YN),
                                            CVPS_SORT_ORDER = Convert.ToInt32(vps.CVPS_SORT_ORDER),
                                            CVPS_VALID_FROM = Convert.ToInt32(vps.CVPS_VALID_FROM.Value)
                                      }).ToList();
            var newVBNExtraProperties = vbnExtraPropertiesTxt.Except(vbnExtraPropertiesDB, new VBNExtraPropComparer());
            int counter = 0;
            foreach (var np in newVBNExtraProperties) {
                F_CAB_VBN_PROPERTIES_SPECIFIED fcvps = new F_CAB_VBN_PROPERTIES_SPECIFIED {
                    CVPS_VBN_CODE = np.CVPS_VBN_CODE_D,
                    CVPS_VBN_PROP_CODE = np.CVPS_PROP_CODE,
                    CVPS_MANDATORY_YN = np.CVPS_MANDATORY_YN,
                    CVPS_SORT_ORDER = np.CVPS_SORT_ORDER,
                    CVPS_VALID_FROM = np.CVPS_VALID_FROM
                };

                EFHelper.ctx.F_CAB_VBN_PROPERTIES_SPECIFIED.AddObject(fcvps);
                counter++;
                if (counter > 50) {
                    EFHelper.ctx.SaveChanges();
                    counter = 0;
                }
            }
            EFHelper.ctx.SaveChanges();
            return 0;
        }

        private static List<VBNCodeRecord> _cachedVBNList = null;
        private List<VBNCodeRecord> _getVBNList() {
            if (_cachedVBNList != null)
                return _cachedVBNList;

            // Update f_Cab_cd_vbn_code with expired_on from textfile
            // Get codes that does not exist in table
            // merge result into projection VBNCodeMinExpired
            // Only show expired VBN-codes if they are used.
            // Add IsNew-property
            string[] filesCode = Directory.GetFiles(Server.MapPath("~/tmp/"), "FP*.txt");
            string fileCode = filesCode[filesCode.Length - 1];
            var vbnCodesTxt = (from line in ReadFrom(fileCode)
                              let record = ParseLineVBNCodes(line)
                              select record).ToList();
            DateTime now = DateTime.Now;
/*            var expiredVBNCodes = vbnCodesTxt.Where(x => x.ExpiredDate < now).ToList();
            var expiredVBNCodesOnly = expiredVBNCodes.Select(x => x.VBNC_VBN_CODE).ToList();

            var vbnCodestoUpdate = EFHelper.ctx.F_CAB_CD_VBN_CODE.Where(x => expiredVBNCodesOnly.Contains(x.VBNC_VBN_CODE));
            foreach (var ve in vbnCodestoUpdate)
            {
                ve.VBNC_EXPIRED_ON = expiredVBNCodes.Single(x => x.VBNC_VBN_CODE == ve.VBNC_VBN_CODE).ExpiredDate;
            }
            EFHelper.ctx.SaveChanges();
*/
            var vbnCodesDB = (from vbn in EFHelper.ctx.F_CAB_CD_VBN_CODE
                             select new VBNCodeRecord {
//                                 VBNC_SEQUENCE = vbn.VBNC_SEQUENCE,
                                 VBNC_VBN_CODE = vbn.VBNC_VBN_CODE,
                                 VBNC_DESC = vbn.VBNC_DESC,
                                 VBNC_FK_VBN_GROUP = vbn.VBNC_FK_VBN_GROUP,
                                 EntryDate = vbn.VBNC_CREATED_ON,
                                 ModifiedDate = vbn.VBNC_MODIFIED_ON,
                                 ExpiredDate = vbn.VBNC_EXPIRED_ON
                             }).ToList();

            var newVBNCodes = vbnCodesTxt.Except(vbnCodesDB, new VBNComparer());
            var result = newVBNCodes.ToList();

            return result;
        }

        public JsonResult AddNewVBNCodes() {
            var vbnlist = _getVBNList();
            var vbnGroupsTXT = vbnlist.Select(x => x.VBNC_FK_VBN_GROUP).ToList();
            var vbnGroupsDBtxt = EFHelper.ctx.F_CAB_CD_VBN_CODE_GROUP.Select(x => x.CDVG_CODE).ToList();
            var vbnGroupsDB = vbnGroupsDBtxt.Select(x => Int32.Parse(x)).ToList();
            var newVBNGroups = vbnGroupsTXT.Except(vbnGroupsDB).ToList();

            // Add new groups
            if (newVBNGroups.Count > 0) {
                string[] filesGroup = Directory.GetFiles(Server.MapPath("~/tmp/"), "FO*.txt");
                string fileGroup = filesGroup[filesGroup.Length - 1];
                var vbnGroupsTxt =  from line in ReadFrom(fileGroup)
                                    let record = ParseLineVBNGroups(line)
                                    select record;
                foreach (var newgroup in newVBNGroups) {
                    var newEntry = vbnGroupsTxt.FirstOrDefault(x => x.CDVG_CODE == newgroup.ToString());
                    F_CAB_CD_VBN_CODE_GROUP vg = new F_CAB_CD_VBN_CODE_GROUP {
                        CDVG_CODE = newEntry.CDVG_CODE,
                        CDVG_DESC = newEntry.CDVG_DESC,
                        CDVG_MAINGROUP = Int32.Parse(newEntry.CDVG_MAINGROUP)
                    };
                    EFHelper.ctx.F_CAB_CD_VBN_CODE_GROUP.AddObject(vg);
                    EFHelper.ctx.SaveChanges();
                }
            }

            // Add new codes
            int counter = 0;
            foreach (var newcode in vbnlist) {
                var vbnGroupTXT = newcode.VBNC_FK_VBN_GROUP.ToString();
                var vbnGroup = EFHelper.ctx.F_CAB_CD_VBN_CODE_GROUP.FirstOrDefault(x => x.CDVG_CODE == vbnGroupTXT);
                F_CAB_CD_VBN_CODE nc = new F_CAB_CD_VBN_CODE {
                    VBNC_VBN_CODE = newcode.VBNC_VBN_CODE,
                    VBNC_DESC = newcode.VBNC_DESC,
                    VBNC_DESC_UPPER = newcode.VBNC_DESC.ToUpper(),
                    VBNC_FK_VBN_GROUP = vbnGroup.CDVG_SEQUENCE,
                    VBNC_EXPIRED_ON = newcode.ExpiredDate,
                    VBNC_CREATED_ON = newcode.EntryDate,
                    VBNC_MODIFIED_ON = newcode.ModifiedDate,
                    VBNC_CREATED_BY = "LogiCAB",
                    VBNC_MODIFIED_BY = "LogiCAB"
                };
                EFHelper.ctx.F_CAB_CD_VBN_CODE.AddObject(nc);
                if (counter % 100 == 0) EFHelper.ctx.SaveChanges();                
                counter++;
            }
            EFHelper.ctx.SaveChanges();
            
            int numAdded = 42;
            return Json(new {
                NewVBNCodes = counter,
                NewVBNGroups = newVBNGroups.Count
            }, JsonRequestBehavior.AllowGet);
        }

        private static VBNCodeRecord ParseLineVBNCodes(string line) {
            //Example: 1;2;1;Agapanthus overig;AGAP OVERIG;;;0;10104101;19850101;;201006080944
            string[] elements = line.Split(';');
            return new VBNCodeRecord {
                VBNC_VBN_CODE = elements[1],
                VBNC_DESC = elements[4],
                VBNC_FK_VBN_GROUP = Int32.Parse(elements[8]),
                EntryDate = DateTime.ParseExact(String.IsNullOrEmpty(elements[9]) ? "21850101" : elements[9], "yyyyMMdd", CultureInfo.CurrentCulture),
                ExpiredDate = DateTime.ParseExact(String.IsNullOrEmpty(elements[10]) ? "21850101" : elements[10], "yyyyMMdd", CultureInfo.CurrentCulture),
                ModifiedDate = DateTime.ParseExact(String.IsNullOrEmpty(elements[11]) ? "218501010000" : elements[11], "yyyyMMddHHmm", CultureInfo.CurrentCulture),
            };
        }
        private static GroupRecord ParseLineVBNGroups(string line) {
            //Example: 16;10100302;Alstroemeria kleinbloemig;19970414;;200310010944
            string[] elements = line.Split(';');
            // VBN Group Codes starting with 1=Flowers, 2,3=Plants, 4=Misc
            string[] maingroups = new String[] { "x", "2", "1", "4" };
            int maingroup = (int)char.GetNumericValue(elements[1].ElementAt(0));

LogiCAB.Web/Views/Shared/Menu/LanguagePartial.cshtml
@using CAB.Data.EF.Models;
@using LogiCAB.Web.DAL;
@using LogiCAB.Web.Domain;
@using CAB.Domain.Helpers;
@{
    var languagesStatic = new List<Tuple<string, string>>();
    languagesStatic.Add(new Tuple<string, string>("nl", "NED"));
    languagesStatic.Add(new Tuple<string, string>("en", "ENG"));

    string toBind = "nl";
    if (Usr.Language == 23 || Usr.Language == 32) {
        toBind = "en";
    }
    
}
<table>
    <tr>
        <td>
            @Html.DevExpress().Button(btnSettings => {
                btnSettings.Name = "logout";
                btnSettings.ControlStyle.CssClass = "button";
                btnSettings.Text = "";
                btnSettings.Images.Image.Url = Url.Content("~/Content/logout.png");
                btnSettings.Images.Image.Height = Unit.Pixel(16);
                btnSettings.Images.Image.Width = Unit.Pixel(16);
                btnSettings.Width = Unit.Percentage(100);
                btnSettings.RouteValues = new { Controller = "User", Action = "LogOff" };
            }).GetHtml()
        </td>
        <td>
            @Html.DevExpress().ComboBox(ccs => {
                ccs.Name = "comboLanguageGlobal";
                ccs.Properties.ShowImageInEditBox = true;
                ccs.Width = Unit.Percentage(100);
                ccs.Height = Unit.Pixel(20);
                ccs.Properties.ItemImage.Height = 20;
                ccs.Properties.ValueType = typeof(string);
                ccs.SelectedIndex = 0;
                foreach (var l in languagesStatic) {
                    ccs.Properties.Items.Add(l.Item2, l.Item1, Url.Content(String.Format("~/Content/flags/{0}.png", l.Item1)));
                }
                ccs.Properties.ClientSideEvents.SelectedIndexChanged = "fnChangeLanguage";
                }).Bind(toBind).GetHtml()
        </td>
    </tr>
</table>



LogiCAB.Web/Views/Shared/Menu/NavBarSystemPartial.cshtml
@using LogiCAB.Web.Domain;
@using CAB.Domain.Helpers;
@Html.DevExpress().NavBar(s => {
    s.Name = "nbFeatures";
    s.AllowExpanding = true;
    s.AllowSelectItem = true;
    s.AutoCollapse = true;
    s.EnableHotTrack = true;
    s.EnableAnimation = true;
    s.SaveStateToCookies = true;

    s.Width = Unit.Percentage(100);
    s.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
    s.ControlStyle.Paddings.Padding = Unit.Pixel(0);

    s.Groups.Add(group => {
        group.Text = Extensions.dict(Usr.Language, "logs and tracing");
        group.HeaderImage.Url = "~/Content/manual.png";
        group.HeaderImage.Height = 16;
        group.HeaderImage.Width = 16;

        group.Items.Add(g => {
            g.Name = "logiofferLog";
            g.Text = "LogiOffer";
            g.Image.Url = "~/Content/manual.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Log/LogiOffer";
        });
        group.Items.Add(g => {
            g.Name = "Logicablog";
            g.Text = "LogiCAB";
            g.Image.Url = "~/Content/manual.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Log/LogiCAB";
        });
        group.Items.Add(g => {
            g.Name = "Logiservicelog";
            g.Text = "LogiService";
            g.Image.Url = "~/Content/manual.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Log/LogiService";
        });
        group.Items.Add(g => {
            g.Name = "Logioffertelog";
            g.Text = "LogiOfferte";
            g.Image.Url = "~/Content/manual.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Log/LogiOfferte";
        });
        group.Items.Add(g => {
            g.Name = "LogiServiceTest";
            g.Text = "LogiServiceCheck";
            g.Image.Url = "~/Content/manual.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.Enabled = false;
            g.NavigateUrl = "~/Log/LogiServiceOfferlist";
        });
        group.Items.Add(g => {
            g.Name = "LogiService";
            g.Text = "LogiService";
            g.Image.Url = "~/Content/globe.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/LogiService/Index";
        });
        group.Items.Add(g => {
            g.Name = "usersOnline";
            g.Text = Extensions.dict(Usr.Language, "users online");
            g.Image.Url = "~/Content/users.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/User/ListOnline";
        });
        group.Items.Add(g => {
            g.Name = "logicabapp";
            g.Text = "LogiCAB App";
            g.Image.Url = "~/Content/logicabapp.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Log/LogiCABApp";
        });        
    });

    s.Groups.Add(group => {
        group.Text = Extensions.dict(Usr.Language, "maintenance");
        group.HeaderImage.Url = "~/Content/cogwheel.png";
        group.HeaderImage.Height = 16;
        group.HeaderImage.Width = 16;

        group.Items.Add(g => {
            g.Name = "vbnlink";
            g.Text = Extensions.dict(Usr.Language, "CAB-VBN Properties");
            g.Image.Url = "~/Content/pending.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/VBN/Link";
        });        
        
        group.Items.Add(g => {
            g.Name = "cabmanage";
            g.Text = Extensions.dict(Usr.Language, "cabmanagement");
            g.Image.Url = "~/Content/assort.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/CAB/Index";
        });
        group.Items.Add(g => {
            g.Name = "cabauthorize";
            g.Text = Extensions.dict(Usr.Language, "cabauthorize");
            g.Image.Url = "~/Content/request.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/CABAuthorize/Index";
        });
        group.Items.Add(g => {
            g.Name = "vbnmanage";
            g.Text = "VBN Code beheer";
            g.Visible = false;
        });
/*        group.Items.Add(g => {
            g.Name = "cabproperties";
            g.Text = Extensions.dict(Usr.Language, "cabproperties");
            g.Image.Url = "~/Content/properties.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/CAB/Properties";
        });*/
        group.Items.Add(g => {
            g.Name = "cabpropertiesKO";
            g.Text = Extensions.dict(Usr.Language, "cabproperties");
            g.Image.Url = "~/Content/update.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/CAB/PropertiesKO";
        });        
        group.Items.Add(g => {
            g.Name = "vbnManagement";
            g.Text = Extensions.dict(Usr.Language, "vbnmanagement");
            g.Image.Url = Url.Content("~/Content/update.png");
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = Url.Action("Index", "VBN");
        });
        group.Items.Add(g => {
            g.Name = "vbnupdate";
            g.Text = Extensions.dict(Usr.Language, "vbn update");
            g.Image.Url = "~/Content/update.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/VBN/Update";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "vbnexpired";
            g.Text = Extensions.dict(Usr.Language, "vbn expired");
            g.Image.Url = "~/Content/update.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/VBN/ExpiredVBN";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "vbnproperties";
            g.Text = "VBN Kenmerken";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "handshakes";
            g.Text = "Handshakes";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "grouptypemaage";
            g.Text = "Groeptype Beheer";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "users";
            g.Text = Extensions.dict(Usr.Language, "users");
            g.Image.Url = "~/Content/users.png";
            g.NavigateUrl = "~/User/List";
            g.Image.Height = 16;
            g.Image.Width = 16;
        });
        group.Items.Add(g => {
            g.Name = "cabgroupmanage";
            g.Text = "CAB Groep Beheer";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "maingroupmanage";
            g.Text = "Hoofd Groep Beheer";
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "orgamanage";
            g.Text = Extensions.dict(Usr.Language, "organisation management");
            g.Image.Url = "~/Content/misc.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Organisation/Index";
        });
        group.Items.Add(g =>
        {
            g.Name = "handshakemanage";
            g.Text = Extensions.dict(Usr.Language, "handshakes");
            g.Image.Url = "~/Content/handshakeBlack.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/HandshakeAdmin/Index";
        });        
        group.Items.Add(g => {
            g.Name = "personamanage";
            g.Text = "Persoon Beheer";
            g.Image.Url = "~/Content/person.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.Visible = false;
        });
        group.Items.Add(g => {
            g.Name = "translations";
            g.Text = Extensions.dict(Usr.Language, "translations");
            g.Image.Url = "~/Content/translations.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Translation/Index";
        });
        group.Items.Add(g => {
            g.Name = "locations";
            g.Text = Extensions.dict(Usr.Language, "locations");
            g.Image.Url = "~/Content/needsupdate.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Location/Index";
        });                
    });

    s.Groups.Add(group => {
        group.Text = Extensions.dict(Usr.Language, "billing");
        group.HeaderImage.Url = "~/Content/invoice.png";
        group.HeaderImage.Height = 16;
        group.HeaderImage.Width = 16;

        group.Items.Add(g => {
            g.Name = "Billing_OverviewB";
            g.Text = Extensions.dict(Usr.Language, "buyers");
            g.Image.Url = "~/Content/order.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Billing/IndexBuyers";
        });
        group.Items.Add(g => {
            g.Name = "Billing_OverviewG";
            g.Text = Extensions.dict(Usr.Language, "growers");
            g.Image.Url = "~/Content/order.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Billing/IndexGrowers";
        });
        group.Items.Add(g => {
            g.Name = "Billing_OverviewKVKService";
            g.Text = Extensions.dict(Usr.Language, "KVKService");
            g.Image.Url = "~/Content/globe.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Billing/IndexKVKService";
        });        
    });

    s.Groups.Add(group => {
        group.Text = "Webshops";
        group.HeaderImage.Url = "~/Content/assort.png";
        group.HeaderImage.Height = 16;
        group.HeaderImage.Width = 16;

        group.Items.Add(g => {
            g.Name = "webshop_versionCheck";
            g.Text = "Versioncheck";
            g.Image.Url = "~/Content/properties.png";
            g.Image.Height = 16;
            g.Image.Width = 16;
            g.NavigateUrl = "~/Webshop/Version";
        });
    });

    s.Groups.Add(group =>
    {
        group.Text = Extensions.dict(Usr.Language, "changemaingroup");
        group.HeaderImage.Url = "~/Content/maingroup.png";
        group.HeaderImage.Height = 16;
        group.HeaderImage.Width = 16;

        foreach (CAB.Domain.Models.Maingroup mg in Usr.Organisation.Maingroups)
        {
            var imgUrl = string.Empty;
            switch (mg.Sequence)
            {
                case 1: //Plant
                    imgUrl = "~/Content/plant.png";
                    break;
                case 2: //Flower
                    imgUrl = "~/Content/flower.png";
                    break;
                case 3: //Fish
                    imgUrl = "~/Content/fish.png";
                    break;
                case 4: //Misc
                    //item1.Image.Url = "";
                    break;
                case 5: //Dryflower
                    imgUrl = "~/Content/dryflower.png";
                    break;
                default:
                    break;
            }
            group.Items.Add(g =>
            {
                g.Name = mg.Description;
                g.Text = Extensions.dict(Usr.Language, mg.Description);
                g.Image.Url = imgUrl;
                g.Image.Height = 16;
                g.Image.Width = 16;
                g.NavigateUrl = String.Format("~/User/setSelectedMainGroup/{0}", mg.Sequence);
            });
        }
    });
}).GetHtml()

LogiCAB.Web/Views/Shared/Menu/ToolBoxPartial.cshtml
@Html.DevExpress().Button(b => {
    b.Name = "btn_Toolbox";
    b.ControlStyle.CssClass = "button";
    b.Text = "Refresh";
    b.Style.Add("font-weight", "bold");
    b.Attributes.CssStyle.Add("margin", "5px;");
    b.Images.Image.Url = "~/Content/refresh.png";
    b.Images.Image.Height = System.Web.UI.WebControls.Unit.Pixel(16);
    b.Images.Image.Width = System.Web.UI.WebControls.Unit.Pixel(16);
    b.Width = System.Web.UI.WebControls.Unit.Pixel(100);
    b.ClientSideEvents.Click = "function(s,e) { gvOrganisationList.ClearFilter(); gvOrganisationList.Refresh(); gvOrganisationList.CancelEdit(); }";
}).GetHtml()