LogiCAB.Web/Controllers/HandshakeController.cs
using LogiCAB.Web.Domain;
using CAB.Data.EF.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using LogiCAB.Web.DAL;
using CAB.Domain.Helpers;
using CAB.Domain.Enums;
using log4net;
using System.Data.Entity.Core.Objects;
using System.Net.Mail;
using System.Configuration;
using System.Threading;
using System.Globalization;
/*
 * Add small Logistic-signup form for transporters.
 * Orga-type: "LOGI". Basic info with Emset-ail, Type
 * 
 * Show this list at the Handshake-detail in Relations.
 * Add the LOGI-organisation to a HandshakeOption-field: Logistics.
 * 
 */
namespace LogiCAB.Web.Controllers {
    [Authorize]
    [HandleError]
    public class HandshakeController : BaseController {
        private string mailOverride;
        public HandshakeController(ILog log) : base(log) {
            mailOverride = ConfigurationManager.AppSettings["mailOverride"];

        
        }
        public ActionResult Index() {
            return View(getHandshakes());
        }

        public ActionResult IndexAdmin() {
            return View(getHandshakesAdmin());
        }

        public ActionResult ListAdmin() {
            return PartialView("ListAdmin", getHandshakesAdmin());
        }

        private static List<Handshake> adminHandshakeCache;
        private static bool adminHandshakeCacheDirty = false;     // Set to true when updated.
        public List<Handshake> getHandshakesAdmin() {
            if (adminHandshakeCache != null && !adminHandshakeCacheDirty) {
                return adminHandshakeCache;
            }
            
            var handshakes = EFHelper.ctx.F_CAB_HANDSHAKE.Select(x => new Handshake {
                seq = x.HAND_SEQUENCE,
                active = x.HAND_BLOCKED_YN,
                request_date = x.HAND_REQUEST_DATE,
                accept_date = x.HAND_ACCEPT_DATE,
                _growerOrga = x.F_CAB_ORGANISATION,
                _buyerOrga = x.F_CAB_ORGANISATION1,
                hndo = x.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault()
            }).ToList();
            adminHandshakeCache = handshakes;
            return adminHandshakeCache;

        }
        public ActionResult IndexAsGrower() {
            return View(getCommHandshakesAsGrower());
        }
        public ActionResult IndexAsBuyer() {
            return View(getCommHandshakesAsBuyer());
        }

        public ActionResult ListAsGrower() {
            return PartialView("ListAsGrower", getCommHandshakesAsGrower());
        }

        public ActionResult ListAsBuyer() {
            return PartialView("ListAsBuyer", getCommHandshakesAsBuyer());
        }

        public ActionResult List() {
            return PartialView("List", getHandshakes());
        }

        public ActionResult ListPending() {
            return PartialView("ListPending", getHandshakes());
        }

        private IEnumerable getCommHandshakesAsGrower() {
            return (from h in EFHelper.ctx.F_CAB_HANDSHAKE.Where(x => x.HAND_FK_ORGA_SEQ_GROWER == Usr.OrganisationSequence)
                    select new Handshake {
                        seq = h.HAND_SEQUENCE,
                        active = h.HAND_BLOCKED_YN,
                        request_date = h.HAND_REQUEST_DATE,
                        accept_date = h.HAND_ACCEPT_DATE,
                        _buyerOrga = h.F_CAB_ORGANISATION1,
                        hndo = EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == h.HAND_SEQUENCE)
                    }).Distinct().ToList();
        }
        private IEnumerable getCommHandshakesAsBuyer() {
            return (from h in EFHelper.ctx.F_CAB_HANDSHAKE.Where(x => x.HAND_FK_ORGA_SEQ_BUYER == Usr.OrganisationSequence)
                    where
                        h.F_CAB_ORGANISATION.F_CAB_ORGA_MAIN_GROUP_MATRIX.Any(x => x.ORMA_FK_MAIN_GROUP == Usr.SelectedMaingroup) &&
                        h.F_CAB_ORGANISATION.F_CAB_ORGANISATION_ADMIN.FirstOrDefault().ORAD_STATUS != ORAD_Status.AFGEMELD
                    select new Handshake {
                        seq = h.HAND_SEQUENCE,
                        active = h.HAND_BLOCKED_YN,
                        request_date = h.HAND_REQUEST_DATE,
                        accept_date = h.HAND_ACCEPT_DATE,
                        _growerOrga = h.F_CAB_ORGANISATION,
                        hndo = EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == h.HAND_SEQUENCE)
                    }).Distinct().ToList();
        }

        public ActionResult HandshakeEditPartial(int id) {
            var h = EFHelper.ctx.F_CAB_HANDSHAKE.SingleOrDefault(x => x.HAND_SEQUENCE == id);
            if (h == null) return PartialView(null);
            return PartialView(new Handshake {
                seq = h.HAND_SEQUENCE,
                active = h.HAND_BLOCKED_YN,
                request_date = h.HAND_REQUEST_DATE,
                accept_date = h.HAND_ACCEPT_DATE,
                _growerOrga = h.F_CAB_ORGANISATION,
                _buyerOrga = h.F_CAB_ORGANISATION1,
                hndo = EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == h.HAND_SEQUENCE)
            });
        }

        public ActionResult UpdateHandshake(int key, string field, string value) {
            //if (field == "active") { // HAND_BLOCKED_YN                
            //    EFHelper.ctx.F_CAB_HANDSHAKE.FirstOrDefault(x => x.HAND_SEQUENCE == key).HAND_BLOCKED_YN = value == "true" ? true : false; 
            //} else if (field == "hndo.HNDO_AUTO_CONFIRM_YN") {
            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_AUTO_CONFIRM_YN = value == "true" ? true : false; 
            //} else if (field == "hndo.HNDO_AUTO_KWB_YN") {
            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_AUTO_KWB_YN = value == "true" ? true : false; 
            //} else if (field == "hndo.HNDO_DELIVERY_TYPE") {
            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_DELIVERY_TYPE = value.ToString(); 
            //} else if (field == "hndo.HNDO_AUTO_EKT_YN") {
            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_AUTO_EKT_YN = value == "true" ? true : false; 
            //} else if (field == "hndo.HNDO_LATEST_DELIVERY_TIME") {
            //    TimeSpan time = TimeSpan.Parse(value);
            //    DateTime selDate = DateTime.Now.Date + time;

            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_LATEST_DELIVERY_TIME = selDate; // 
            //} else if (field == "hndo.HNDO_FK_ADDR_SEQ") {
            //    EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key).HNDO_FK_ADDR_SEQ = -1; //
            //}
            //EFHelper.ctx.SaveChanges();
            //return null;
            Log.InfoFormat("UpdateHandshake called: Username: {0},\n\t Key: {1}, Field: {2}, Value: {3}", Usr.LoginName, key, field, value);
            var dbObjH = EFHelper.ctx.F_CAB_HANDSHAKE.FirstOrDefault(x => x.HAND_SEQUENCE == key);
            var dbObj = EFHelper.ctx.F_CAB_HANDSHAKE_OPTIONS.FirstOrDefault(x => x.HNDO_FK_HAND_SEQ == key);
            if (field == "active") { // HAND_BLOCKED_YN                
                dbObjH.HAND_BLOCKED_YN = value == "true";
                short ofhdDeletedYN = value == "true" ? (short)1 : (short)0;
                DateTime nowTime = DateTime.Now;
                //                var typeSequence = userinfo.orgaTypeSequence;
                if (Usr.OrganisationType == OrgaType.Grower) {
                    var buyerSequence = dbObjH.F_CAB_ORGANISATION1.F_CAB_BUYER.FirstOrDefault().BUYR_SEQUENCE;
                    var validOffers = (from o in EFHelper.ctx.F_CAB_OFFER_HEADERS
                                       where
                                         o.OFHD_VALID_TO > nowTime
                                         && o.OFHD_FK_GROWER == Usr.OrgaTypeSequence
                                         && o.OFHD_FK_BUYER == buyerSequence
                                       select o.OFHD_SEQUENCE).ToList();
                    foreach (var o in EFHelper.ctx.F_CAB_OFFER_HEADERS.Where(x => validOffers.Contains(x.OFHD_SEQUENCE))) {
                        o.OFHD_DELETED_YN = ofhdDeletedYN;
                        o.OFHD_OFFER_CAPTION_SEQ = (Int16)0;
                    }
                } else if (Usr.OrganisationType == OrgaType.Buyer) {
                    var growerSequence = dbObjH.F_CAB_ORGANISATION.F_CAB_GROWER.FirstOrDefault().GROW_SEQUENCE;
                    var validOffers = (from o in EFHelper.ctx.F_CAB_OFFER_HEADERS
                                       where
                                         o.OFHD_VALID_TO > nowTime
                                         && o.OFHD_FK_GROWER == growerSequence
                                         && o.OFHD_FK_BUYER == Usr.OrgaTypeSequence
                                       select o.OFHD_SEQUENCE).ToList();
                    foreach (var o in EFHelper.ctx.F_CAB_OFFER_HEADERS.Where(x => validOffers.Contains(x.OFHD_SEQUENCE))) {
                        o.OFHD_DELETED_YN = ofhdDeletedYN;
                        o.OFHD_OFFER_CAPTION_SEQ = (Int16)0;
                    }
                }
            } else if (field == "hndo.HNDO_AUTO_CONFIRM_YN") {
                dbObj.HNDO_AUTO_CONFIRM_YN = value == "true";
            } else if (field == "hndo.HNDO_AUTO_KWB_YN") {
                dbObj.HNDO_AUTO_KWB_YN = value == "true";
            } else if (field == "hndo.HNDO_DELIVERY_TYPE") {

LogiCAB.Web/Views/Organisation/AddressGridPartial.cshtml
@using CAB.Data.EF.Models;
@using System.Drawing;
@using System.Web.UI.WebControls;
@model IQueryable<F_CAB_ADDRESS>
@Html.DevExpress().GridView(s => {
    s.Name = "gvAddressGrid";
    s.KeyFieldName = "ADDR_SEQUENCE";
    s.Styles.Table.BackColor = Color.PaleGoldenrod;
    s.Width = Unit.Pixel(610);
//    s.CallbackRouteValues = new { Controller = "Assortiment", Action = "CABPropertiesPartial" };
    s.Columns.Add(column => {
        column.FieldName = "ADDR_STREET";
        column.Caption = "Straatnaam";
    });
    s.Columns.Add(column => {
        column.FieldName = "ADDR_NO";
        column.Caption = "Nummer";
        column.Width = Unit.Pixel(100);
    });
    s.Columns.Add(column => {
        column.FieldName = "ADDR_ZIPCODE";
        column.Caption = "Postcode";
        column.Width = Unit.Pixel(25);
    });
    s.Columns.Add(column => {
        column.FieldName = "ADDR_CITY";
        column.Visible = false;
        column.Caption = "Plaatsnaam";
        column.SortIndex = 1;
        column.SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
    });
}).Bind(Model).GetHtml()

LogiCAB.Web/Views/Organisation/CreateLoginPartial.cshtml
@using CAB.Domain.Enums;
@using LogiCAB.Web.Domain;
@model int
<input type="hidden" name="orgaSequence" id="orgaSequence" value="@Model">
<table>
    <tr>

        <td>
            <table border="0">

                <tr>
                    <td>

                        <h4>Person</h4>
                    </td>
                    <td>
                        &nbsp;
                    </td>
                </tr>
                <tr>
                    <td>Last name</td>
                    <td>
                        <input type="text" size="24" name="persLastName" id="persLastName" />
                    </td>
                </tr>
                <tr>
                    <td>
                        First name
                    </td>
                    <td>
                        <input type="text" size="12" name="persFirstName" id="persFirstName" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Middle name
                    </td>
                    <td>
                        <input type="text" size="12" name="persMiddleName" id="persMiddleName" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Email
                    </td>
                    <td>
                        <input type="text" size="12" name="persEmail" id="persEmail" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Phone
                    </td>
                    <td>
                        <input type="text" size="12" name="persPhone" id="persPhone" />
                    </td>
                </tr>

            </table>
            <table border="0">
                <tr>
                    <td>
                        <h4>Login</h4>
                    </td>
                    <td>
                        &nbsp;
                    </td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>
                        <input type="text" size="12" name="loginUsernamePerson" id="loginUsernamePerson" onkeyup="CheckLoginName();" />
                        <img src="~/Content/ok.png" height="24" style="float: right; display:none;" id="loginUsernamePic">
                        <img src="~/Content/delete.png" height="24" style="float: right; display:none;" id="loginUsernamePicExists">
                    </td>
                </tr>
                <tr>
                    <td>
                        Password
                    </td>
                    <td>
                        <input type="text" size="12" name="loginPassword" id="loginPassword" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Language
                    </td>
                    <td>
                        @*<input type="text" size="12" name="loginLanguage" />*@
                        @Html.DevExpress().ComboBox(ccs => {
                       ccs.Name = "combo_login_ccP";
                       ccs.Properties.ShowImageInEditBox = true;

                       ccs.Properties.ItemImage.Height = 16;
                       ccs.SelectedIndex = 1;
                       ccs.Properties.Items.Add("NL", 1, Url.Content("~/Content/flags/nl.png"));
                       ccs.Properties.Items.Add("ENG", 32, Url.Content("~/Content/flags/gb.png"));
                       ccs.Properties.Items.Add("DUI", 31, Url.Content("~/Content/flags/de.png"));
                       ccs.Properties.Items.Add("NOR", 36, Url.Content("~/Content/flags/no.png"));

                       //               ccs.SelectedIndex = Model.Orad.Type;
                       //               ccs.Properties.ClientSideEvents.SelectedIndexChanged = "function(s,e) { orad_Member_OnValueChanged(s,e, " + Model.Orad.Sequence + ") }";
                       //                        ccs.Properties.ClientSideEvents.SelectedIndexChanged = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                       //ccs.Properties.ClientSideEvents.TextChanged = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                       //                        ccs.Properties.ClientSideEvents.CloseUp = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                       //                        ccs.Properties.ClientSideEvents.LostFocus = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                   }).GetHtml()
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:right;padding-right:5px;">
                        @Html.DevExpress().Button(btnSettings => {
                       btnSettings.Name = "btn_createLogin";
                       btnSettings.ControlStyle.CssClass = "button";
                       btnSettings.Text = "Create Login";
                       btnSettings.Style.Add("font-weight", "bold");
                       btnSettings.Attributes.CssStyle.Add("margin", "5px;");
                       //btnSettings.Attributes.CssStyle.Add("padding-top", "13px;");
                       btnSettings.Images.Image.Url = "~/Content/plus.png";
                       btnSettings.Images.Image.Height = System.Web.UI.WebControls.Unit.Pixel(10);
                       btnSettings.Images.Image.Width = System.Web.UI.WebControls.Unit.Pixel(10);
                       btnSettings.Width = System.Web.UI.WebControls.Unit.Pixel(160);
                       btnSettings.ClientSideEvents.Click = "fnCreateLogin";
                   }).GetHtml()
                    </td>

                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td>

                        <h4>Info</h4>
                        <div id="infoPanelLogin"></div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<script type="text/html" id="newLoginTemplate">
    <table border="1">
        <tr>
            <td>Person</td>
            <td>##persName##</td>
        </tr>
        <tr>
            <td>Login</td>
            <td>##logiName##</td>
        </tr>
    </table>
</script>

LogiCAB.Web/Views/Organisation/CreateOrganisation.cshtml
@using CAB.Domain.Enums;
@using LogiCAB.Web.Domain;
@model CAB.Domain.Models.Organisation

<form id="newOrgaForm">
    <table>
        <tr>
            <td>
                <img src="~/Content/plus.png" height="24" style="float: left;margin-top: 4px;padding: 5px;">
                <h3> New Organisation</h3>
            </td>
            <td style="text-align:right;padding-right:5px;">
                @Html.DevExpress().Button(btnSettings => {
           btnSettings.Name = "btn_createOrga";
           btnSettings.ControlStyle.CssClass = "button";
           btnSettings.Text = "Create Organisation";
           btnSettings.Style.Add("font-weight", "bold");
           btnSettings.Attributes.CssStyle.Add("margin", "5px;");
           //btnSettings.Attributes.CssStyle.Add("padding-top", "13px;");
           btnSettings.Images.Image.Url = "~/Content/plus.png";
           btnSettings.Images.Image.Height = System.Web.UI.WebControls.Unit.Pixel(10);
           btnSettings.Images.Image.Width = System.Web.UI.WebControls.Unit.Pixel(10);
           btnSettings.Width = System.Web.UI.WebControls.Unit.Pixel(160);
           btnSettings.ClientSideEvents.Click = "fnCreateOrganisation";
       }).GetHtml()
            </td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <td>
                            Naam
                        </td>
                        <td>
                            <input type="text" size="24" name="orgaName" id="orgaName" />
                            <img src="/LogiCAB/Content/ok.png" height="24" style="float: right; display:none;" id="orgaNamePic">
                            <br />
                        </td>
                    </tr>

                    <tr>
                        <td>
                            E-Mail
                        </td>
                        <td>
                            <input type="text" size="24" name="orgaEmail" id="orgaEmail" />
                            <br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Type
                        </td>
                        <td>
                            <hr />
                            <input type="radio" name="orgaType" value="BUYR" />Buyer<br />
                            <input type="radio" name="orgaType" value="GROW" />Grower<br />
                            <input type="radio" name="orgaType" value="COMM" />Commisionaire<br />
                            <input type="radio" name="orgaType" value="LOGP" />Logistics<br />
                            <br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Maingroups
                        </td>
                        <td>
                            <hr />
                            <input type="checkbox" name="orgaMaingroup" class="orgaMaingroup" value="2">Flowers<br />
                            <input type="checkbox" name="orgaMaingroup" class="orgaMaingroup" value="1" />Plants<br />
                            <input type="checkbox" name="orgaMaingroup" class="orgaMaingroup" value="4" />Misc<br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Functions
                        </td>
                        <td>
                            <hr />
                            @foreach (Function f in LogiCAB.Web.Controllers.OrganisationController.Functions) {
                                var fSeq = (int)f;
                                
                                if (f == Function.LOGIOFFERTE || f == Function.BUY_STOCK || f == Function.BUY_OFFER) {
                                    <input type="checkbox" name="orgaFunctions" class="orgaFunctions" value="@fSeq"><span style="color:green; font-weight:bold;">@f</span><br />
                                } else {
                                    <input type="checkbox" name="orgaFunctions" class="orgaFunctions" value="@fSeq">@f<br />
                                }

                            }
                        </td>







                    </tr>
                </table>
               
            </td>
            <td style="vertical-align:top; border-left: 2px dotted black;padding-left:10px;">
                <table border="0">
                    <tr>
                        <td>
                            <h4>Address</h4>
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>Street</td>
                        <td>
                            <input type="text" size="48" name="addrStreet" id="addrStreet" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nr
                        </td>
                        <td>
                            <input type="text" size="12" name="addrNr" id="addrNr" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Zipcode
                        </td>
                        <td>
                            <input type="text" size="12" name="addrZip" id="addrZip" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            City
                        </td>
                        <td>
                            <input type="text" size="24" name="addrCity" id="addrCity" />
                        </td>
                    </tr>
                </table>
                <table border="0">
                    <tr>
                        <td>
                            <h4>Person</h4>
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>Last name</td>
                        <td>
                            <input type="text" size="24" name="persLastName" id="persLastName" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            First name
                        </td>
                        <td>
                            <input type="text" size="12" name="persFirstName" id="persFirstName" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Middle name
                        </td>
                        <td>
                            <input type="text" size="12" name="persMiddleName" id="persMiddleName" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Emai
                        </td>
                        <td>
                            <input type="text" size="12" name="persEmail" id="persEmail" />
                        </td>
                    </tr>

                </table>
                <table border="0">
                    <tr>
                        <td>
                            <h4>Login</h4>
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>Username</td>
                        <td>
                            <input type="text" size="12" name="loginUsername" id="loginUsername" />
                            <img src="~/Content/ok.png" height="24" style="float: right; display:none;" id="loginUsernamePic">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Password
                        </td>
                        <td>
                            <input type="text" size="12" name="loginPassword" id="loginPassword" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Language
                        </td>
                        <td>
                            @*<input type="text" size="12" name="loginLanguage" />*@
                            @Html.DevExpress().ComboBox(ccs => {
                           ccs.Name = "combo_login_cc";
                           ccs.Properties.ShowImageInEditBox = true;

                           ccs.Properties.ItemImage.Height = 16;
                           ccs.SelectedIndex = 1;
                           ccs.Properties.Items.Add("NL", 1, Url.Content("~/Content/flags/nl.png"));
                           ccs.Properties.Items.Add("ENG", 32, Url.Content("~/Content/flags/gb.png"));
                           ccs.Properties.Items.Add("DUI", 31, Url.Content("~/Content/flags/de.png"));
                           ccs.Properties.Items.Add("NOR", 36, Url.Content("~/Content/flags/no.png"));

                           //               ccs.SelectedIndex = Model.Orad.Type;
                           //               ccs.Properties.ClientSideEvents.SelectedIndexChanged = "function(s,e) { orad_Member_OnValueChanged(s,e, " + Model.Orad.Sequence + ") }";
                           //                        ccs.Properties.ClientSideEvents.SelectedIndexChanged = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                           //ccs.Properties.ClientSideEvents.TextChanged = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                           //                        ccs.Properties.ClientSideEvents.CloseUp = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                           //                        ccs.Properties.ClientSideEvents.LostFocus = String.Format("function (s, e) {{ OnValueChanged(s, 'hndo.{0}', '{1}', '{2}'); }}", field.HNOF_FIELD, Model.seq, Url.Action("UpdateHandshake", "Handshake", null));
                       }).GetHtml()
                        </td>
                    </tr>

                </table>
            </td>
            <td style="vertical-align:top; border-left: 2px dotted black;padding-left:10px;">
                <h4>Info</h4>
                <div id="infoPanel"></div>
            </td>
        </tr>
    </table>
</form>
<script type="text/html" id="newOrgaTemplate">
    <table border="1">
        <tr>
            <td>Organisation</td>
            <td>##orgaName##</td>
        </tr>
        <tr>
            <td>Person</td>
            <td>##persName##</td>
        </tr>
        <tr>
            <td>Login</td>
            <td>##logiName##</td>
        </tr>
</table>
</script>

LogiCAB.Web/Views/Organisation/OrgaModulesPartial.cshtml
@model List<OrganisationFunction>

<ul>
    @foreach (OrganisationFunction of in Model) {
        <li>@of.Code</li>

    }
</ul>